targets:
  $default:
    builders:
      mini_server_generator|mini_repository:
        enabled: true

builders:
  mini_repository:
    target: ":mini_server_generator"
    import: "package:mini_server_generator/mini_server_generator.dart"
    builder_factories: ["miniRepositoryBuilder"]
    build_extensions: { ".dart": [".mini_repository.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
