name: mini_server_generator
description: Code generator for mini_server P2P framework.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  analyzer: any
  build: any
  source_gen: any
  mini_server_annotations:
    path: ../mini_server_annotations
